export const ActionTypes={
    CREATE_WEIGHTLOG:"CREATE_WEIGHTLOG",
    READ_WEIGHTLOG:"READ_WEIGHTLOG",
    UPDATE_WEIGHTLOG:"UPDATE_WEIGHTLOG",
    DELETE_WEIGHTLOG:"DELETE_WEIGHTLOG",
    READ_WEIGHTLOG_BYID:"READ_WEIGHTLOG_BYID"
};